require('dotenv').config();

module.exports = {
  DEV_DATABASE_URL: process.env.DEV_DATABASE_URL,
  DATABASE_URL_TEST: process.env.DATABASE_URL,
  DATABASE_URL: process.env.DATABASE_URL,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
  LINKEDIN_API_KEY: process.env.LINKEDIN_API_KEY,
  LINKEDIN_SECRET_KEY: process.env.LINKEDIN_SECRET_KEY
};
