require('dotenv').config();

module.exports = {
  DEV_DATABASE_URL: process.env.DEV_DATABASE_URL,
  DATABASE_URL_TEST: process.env.DATABASE_URL,
  DATABASE_URL: process.env.DATABASE_URL,
  GITHUB_CLIENT_ID: '',
  GITHUB_CLIENT_SECRET: '',
  FACEBOOK_APP_ID: '371824086789568',
  FACEBOOK_APP_SECRET: '4e34d6695db3c168a152578d77154e2c',
  LINKEDIN_API_KEY: '',
  LINKEDIN_SECRET_KEY: ''
};
